force-app/main/default/objects/JSON_Generator__mdt/JSON_Generator__mdt.object-meta.xml
<CustomObject>
    <label>JSON Generator</label>
    <pluralLabel>JSONs Generator</pluralLabel>
</CustomObject>

force-app/main/default/objects/JSON_Generator__mdt/fields/Callout_Name__c.field-meta.xml
<CustomField>
    <fullName>Callout_Name__c</fullName>
    <description>The unique name of the callout has to be common for all the same callout JSON Generator records, System uses this value to get all the JSON Generator records</description>
    <label>Callout Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Is_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the property has been disabled and will not be utilized by the framework.</description>
    <label>Is Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Is_Start__c.field-meta.xml
<CustomField>
    <fullName>Is_Start__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates the starting point of the JSON Generator.</description>
    <label>Is Start</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ValidateJSONCreation.cls
public class ValidateJSONCreation {

    @AuraEnabled(cacheable=true)
    public static List<String> getCalloutNames(){
        Set<String> calloutNames = new Set<String>();
        calloutNames.add('qweqweqweqwe');
        calloutNames.add('asdasdasd');
        for(JSON_Generator__mdt jsonGenerator: [SELECT Callout_Name__c FROM JSON_Generator__mdt WHERE Is_Disabled__c = false AND Is_Start__c = true]){
            calloutNames.add(jsonGenerator.Callout_Name__c);
        }
        return new List<String>(calloutNames);
    }

    @AuraEnabled
    public static String generateJSON(String calloutName, String whereClause){
        JSONGeneratorHandler jsonHandler = new JSONGeneratorHandler(calloutName, whereClause);
        jsonHandler.isBeautifiedJSON = true;
        jsonHandler.includeNullValues = true;
        return jsonHandler.getJSON();
    }

}