force-app/main/default/objects/JSON_Generator__mdt/JSON_Generator__mdt.object-meta.xml
<CustomObject>
    <label>JSON Generator</label>
    <pluralLabel>JSONs Generator</pluralLabel>
</CustomObject>

force-app/main/default/objects/JSON_Generator__mdt/fields/Apex_Class_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_API_Name__c</fullName>
    <description>The class name which implements JSONGeneratorHandler.JSONPropertyInterface interface, to get the apex logic based driven value for JSON record.</description>
    <label>Apex Class API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Callout_Name__c.field-meta.xml
<CustomField>
    <fullName>Callout_Name__c</fullName>
    <description>The unique name of the callout has to be common for all the same callout JSON Generator records, System uses this value to get all the JSON Generator records</description>
    <label>Callout Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>To identify if the data has to be added as String, Number or Boolean in the JSON object.</description>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Is_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the property has been disabled and will not be utilized by the framework.</description>
    <label>Is Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Is_Start__c.field-meta.xml
<CustomField>
    <fullName>Is_Start__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag indicates the starting point of the JSON Generator.</description>
    <label>Is Start</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Object_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Field_API_Name__c</fullName>
    <label>Object Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Parent_JSON_Generator__c.field-meta.xml
<CustomField>
    <fullName>Parent_JSON_Generator__c</fullName>
    <label>Parent JSON Generator</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <description>JSON object property name.</description>
    <label>Property Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Array</fullName>
                <default>true</default>
                <label>Array</label>
            </value>
            <value>
                <fullName>Object</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/sObject_Name__c.field-meta.xml
<CustomField>
    <fullName>sObject_Name__c</fullName>
    <label>sObject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JSON_Generator__mdt/fields/Static_Value__c.field-meta.xml
<CustomField>
    <fullName>Static_Value__c</fullName>
    <description>If we want to setup the static value, rather than the object record drived value, this field should have data.</description>
    <label>Static Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JSONGeneratorHandler.cls
public class JSONGeneratorHandler {

    private String calloutName;
    private sObject sobjectRecord;
    
    private JSON_Generator__mdt startingProperty; 
    private Map<String, List<JSON_Generator__mdt>> jsonPropertyMap; 
    private JSONGenerator generator;
	
	public boolean includeNullValues;
	public boolean isBeautifiedJSON;
    
    public class JSONGeneratorException extends Exception {}

    public interface JSONPropertyInterface {
        String getValue(sObject record);
    }
    
    public JSONGeneratorHandler(String calloutName, sObject sobjectRecord){
        this.calloutName = calloutName;
        this.sobjectRecord = sobjectRecord;
        this.jsonPropertyMap = new Map<String, List<JSON_Generator__mdt>>();
		this.includeNullValues = false;
        this.initialize(null);
        this.isBeautifiedJSON = false;
    }
    
    public JSONGeneratorHandler(String calloutName, String whereClause){
        this.calloutName = calloutName;
        this.jsonPropertyMap = new Map<String, List<JSON_Generator__mdt>>();
		this.includeNullValues = false;
        this.initialize(whereClause);
        this.isBeautifiedJSON = false;
    }
    
    public String getJSON(){
        if(this.startingProperty == null){
            throw new JSONGeneratorException('Starting point not found.');
        }
        if(this.sobjectRecord == null){
            throw new JSONGeneratorException('Mapping record not found.');
        }
        generator = JSON.createGenerator(isBeautifiedJSON);
        addJSONProperty(startingProperty);
        return generator.getAsString();
    }
    
    private void addJSONProperty(JSON_Generator__mdt property){
        if(property.Property_Type__c == 'Array'){
			generator.writeFieldName(property.Property_Name__c);
            generator.writeStartArray();
            processAllChilds(property.DeveloperName);
            generator.writeEndArray();
            
        }else if(property.Property_Type__c == 'Object'){
            generator.writeStartObject();
            processAllChilds(property.DeveloperName);
            generator.writeEndObject();
            
        }else if(property.Property_Type__c == 'Value'){
			String fieldValue;
            if(property.Apex_Class_API_Name__c == null && property.Static_Value__c == null){
                this.writeJSONValue(property.Property_Name__c, this.getFieldValue(property.Object_Field_API_Name__c), property.Data_Type__c);
            }else if(property.Apex_Class_API_Name__c == null && property.Static_Value__c != null){
                this.writeJSONValue(property.Property_Name__c, property.Static_Value__c, property.Data_Type__c);
			}else if(property.Apex_Class_API_Name__c != null && property.Static_Value__c == null){
                JSONPropertyInterface propInterface = (JSONPropertyInterface) Type.forName(property.Apex_Class_API_Name__c).newInstance();
                this.writeJSONValue(property.Property_Name__c, propInterface.getValue(sobjectRecord), property.Data_Type__c);
            }
        }
    }
    
    private void processAllChilds(String parentName){
        for(JSON_Generator__mdt property : this.jsonPropertyMap.get(parentName)){
            addJSONProperty(property);
        }
    }
    
    private void initialize(String whereClause){
        String sobjectName = null;
        Set<String> soqlFields = new Set<String>();
        for(JSON_Generator__mdt jsonGeneratorRec : [SELECT  DeveloperName, 
                                                            Apex_Class_API_Name__c, 
                                                            Is_Start__c, 
                                                            Object_Field_API_Name__c, 
                                                            Parent_JSON_Generator__c, 
                                                            Property_Name__c, 
                                                            Property_Type__c,
                                                            sObject_Name__c,
															Static_Value__c,
                                                            Data_Type__c
                                                    FROM    JSON_Generator__mdt
                                                    WHERE   Callout_Name__c = :this.calloutName
                                                    AND     Is_Disabled__c = false]){
            if(jsonGeneratorRec.Is_Start__c){
                startingProperty = jsonGeneratorRec;
                sobjectName = jsonGeneratorRec.sObject_Name__c;
            }
            if(String.isNotEmpty(jsonGeneratorRec.Parent_JSON_Generator__c)){
                if(!jsonPropertyMap.containsKey(jsonGeneratorRec.Parent_JSON_Generator__c)){
                    jsonPropertyMap.put(jsonGeneratorRec.Parent_JSON_Generator__c, new List<JSON_Generator__mdt>());
                }
                jsonPropertyMap.get(jsonGeneratorRec.Parent_JSON_Generator__c).add(jsonGeneratorRec);
                if(String.isNotEmpty(jsonGeneratorRec.Object_Field_API_Name__c)){
                    soqlFields.add(jsonGeneratorRec.Object_Field_API_Name__c);
                }
            }
        }
        if(String.isNotEmpty(whereClause) && soqlFields.size() > 0){
            getRecord(sobjectName, soqlFields, whereClause);
        }
    }
    
    private void getRecord(String sobjectName, Set<String> soqlFields, String whereClause){
        if(startingProperty == null){
            throw new JSONGeneratorException('Starting point not found.');
        }
        try{
            List<sObject> sobjList = Database.query('SELECT '+String.join(new List<String>(soqlFields), ', ')+' FROM '+sobjectName+' WHERE '+whereClause);
            if(sobjList.size() > 1){
                throw new JSONGeneratorException('More than one record found, Please refine the where clause.');
            }
            if(sobjList.size() == 0){
                throw new JSONGeneratorException('No record found, Please refine the where clause.');
            }
            if(sobjList.size() == 1)
                this.sobjectRecord = sobjList[0];
        }catch(Exception ex){
            throw ex;
        }
    }
    
    private String getFieldValue(String fieldName){
        List<String> objectFields = fieldName.split('\\.');
        sObject record = this.sobjectRecord;
        String value = '';
        for(Integer i = 0; i < objectFields.size(); i++){
            if(i == objectFields.size() - 1){
                value = String.valueOf(record.get(objectFields[i]));
            }else{
                record = record.getSobject(objectFields[i]);
            }
        }
        return value;
    }

    private void writeJSONValue(String property, String value, String dataType){
        if(String.isEmpty(property) && !String.isEmpty(value)){
            if(dataType == 'Number'){
                generator.writeNumber(Decimal.valueOf(value));
            }else if(dataType == 'Boolean'){
                generator.writeBoolean(Boolean.valueOf(value));
            }else{
                generator.writeString(value);
            }
        }else if(!String.isEmpty(property) && !String.isEmpty(value)){
            if(dataType == 'Number'){
                generator.writeNumberField(property, Decimal.valueOf(value));
            }else if(dataType == 'Boolean'){
                generator.writeBooleanField(property, Boolean.valueOf(value));
            }else{
                generator.writeStringField(property, value);
            }
        }else if(!String.isEmpty(property) && String.isEmpty(value) && includeNullValues){
            generator.writeNullField(property);
        }
    }
    
}